backend:
  name: github
  repo: adn7n/galactic-games-echecs
  branch: main

media_folder: public/images

collections:
  - name: pages
    label: Pages
    files:
      - name: home
        label: Page principale
        file: src/content/home.json
        fields:
          - { label: Titre, name: title, widget: string }
          - { label: Description, name: description, widget: text }
          - { label: Année, name: year, widget: string }
          - { label: Date affichée, name: date, widget: string }
          - { label: Date courte, name: dateShort, widget: string }
          - { label: Date compte à rebours, name: targetDate, widget: string }
          - { label: Prix inscription, name: price, widget: string }
          - { label: Capacité max, name: capacity, widget: string }
          - { label: Ville, name: city, widget: string }
          - { label: Nom du club, name: club, widget: string }
          - { label: IBAN, name: iban, widget: string }
          - { label: Bénéficiaire IBAN, name: ibanBeneficiaire, widget: string }
          - { label: Adresse IBAN, name: ibanAdresse, widget: string }
