backend:
  name: github
  repo: adn7n/galactic-games-echecs
  branch: main

media_folder: public/images

collections:
  - name: pages
    label: Infos générales
    files:
      - name: home
        label: Infos du tournoi
        file: src/content/home.json
        fields:
          - { label: Année, name: year, widget: string }
          - { label: Date affichée, name: date, widget: string }
          - { label: Prix inscription, name: price, widget: string }
          - { label: Ville, name: city, widget: string }
          - { label: Nom du club, name: club, widget: string }
          - { label: IBAN, name: iban, widget: string }
      - name: rewards
        label: Récompenses
        file: src/content/rewards.json
        fields:
          - label: Prix participants
            name: participantPrize
            widget: text
          - label: Liste des prix
            name: prizes
            widget: list
            fields:
              - { label: Nom, name: name, widget: string }
              - { label: Disponibilité, name: availability, widget: string }
              - { label: Description, name: description, widget: string }
              - label: Caractéristiques
                name: specs
                widget: list
                field: { label: Spec, name: spec, widget: string }
